#Prometheus deployment, note the meta data matching the service monitor
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: torifirstapp
spec:
  serviceMonitorSelector:
    matchLabels:
      app: torifirstapp
  resources:
    requests:
      memory: 400Mi
#Service monitor deployment: note the selector and namespace selector, which tie the service monitor to an app
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: torifirstapp
  labels:
    app: torifirstapp
spec:
  selector:
    matchLabels:
      app: torifirstapp
  namespaceSelector:
    matchNames:
    - default
  endpoints:
  - port: web
    interval: 5s
#Service deployment: Exposes the prometheus instance to navigation from a UI perspective
---
apiVersion: v1
kind: Service
metadata:
  labels:
    prometheus: torifirstapp
  name: prometheus-torifirstapp
spec:
  ports:
  - name: web
    port: 9090
    targetPort: web
  selector:
    prometheus: torifirstapp
